### ISSUE TITLE
[BUG] One member of Multi-node Etcd start its own cluster as its data-dir structure is invalid which triggers the restoration of single member.

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-druid#361]
**Describe the bug:**
When creating a new `etcd` multi-node cluster it can happen that **multiple clusters** are created instead of one cluster with multiple members. As a result, consumers get a single `etcd-client` service which is backed by distinct clusters.

Etcd-Druid and all involved components use a static bootstrapping procedure as described [here](https://etcd.io/docs/v3.4/op-guide/clustering/#static).
In combination with the StatefulSet's [parallel podManagementPolicy](https://github.com/gardener/etcd-druid/blob/4da816d7247971c5f47cb529b7df2894cb21e1bd/charts/etcd/templates/etcd-statefulset.yaml#L19) it sometimes happen that two or more pods don't detect an existing cluster which makes them to create a new cluster (due to `--initial-cluster-state new`) at the same time.

In this example we saw it for two pods which belonged to the same StatefulSet (please also note the version difference):

- etcd-main-0
```
2022-06-24T15:08:15.87671756Z stderr F 2022-06-24 15:08:15.876585 I | etcdserver: setting up the initial cluster version to 3.0
```

- etcd-main-2
```
2022-06-24T15:08:23.391710822Z stderr F 2022-06-24 15:08:23.391621 I | etcdserver: setting up the initial cluster version to 3.4
```

After all the pods were running we constantly observed logs like:

```
2022-06-24T15:08:25.488303476Z stderr F 2022-06-24 15:08:25.488156 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[1e2acb0b00e637d5]=cdf818194e3a8c32, local=dd673093ade40ad6)
2022-06-24T15:08:25.488463226Z stderr F 2022-06-24 15:08:25.488363 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[1e2acb0b00e637d5]=cdf818194e3a8c32, local=dd673093ade40ad6)
2022-06-24T15:08:25.565269748Z stderr F 2022-06-24 15:08:25.564967 E | rafthttp: request sent was ignored (cluster ID mismatch: remote[1e2acb0b00e637d5]=cdf818194e3a8c32, local=dd673093ade40ad6)
2022-06-24T15:08:25.586832244Z stderr F 2022-06-24 15:08:25.586699 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[1e2acb0b00e637d5]=cdf818194e3a8c32, local=dd673093ade40ad6)
```

**Expected behavior:**
Etcd-Druid to create a single cluster with the amount of replicas configured in the `etcd` resource.

**How To Reproduce (as minimally and precisely as possible):**
Create a mutli-node `etcd` cluster with Etcd-Druid.

**Environment (please complete the following information):**
 - Etcd-druid version/commit ID : `v0.10.0`

**Anything else we need to know?**:
We analyzed this issue together with @rfranzke and @timebertt and in addition checked how [KinD](https://github.com/kubernetes-sigs/kind/) bootstraps multi-node etcd clusters. Turned out that they create a new cluster once with a single member and then scale-up by one member at a time:

- Pod-0
```
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.18.0.4:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://172.18.0.4:2380
    - --initial-cluster=test-control-plane=https://172.18.0.4:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.4:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://172.18.0.4:2380
    - --name=test-control-plane
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```

- Pod-1
```
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.18.0.2:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://172.18.0.2:2380
    - --initial-cluster=test-control-plane=https://172.18.0.4:2380,test-control-plane2=https://172.18.0.2:2380
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.2:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://172.18.0.2:2380
    - --name=test-control-plane2
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```
- Pod-2
```
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.18.0.3:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --experimental-initial-corrupt-check=true
    - --initial-advertise-peer-urls=https://172.18.0.3:2380
    - --initial-cluster=test-control-plane3=https://172.18.0.3:2380,test-control-plane=https://172.18.0.4:2380,test-control-plane2=https://172.18.0.2:2380
    - --initial-cluster-state=existing
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://172.18.0.3:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://172.18.0.3:2380
    - --name=test-control-plane3
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
```

Thanks for you input @timebertt and @rfranzke.
