### ISSUE TITLE
[BUG] Hostpath not configureable via backup secret

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-druid#407]
**Describe the bug:**
Earlier it was possible to configure the `hostPath` used for the local backup provider via the referenced secret in `etcd.spec.backup.store.secretRef`, e.g.:

```
apiVersion: v1
kind: Secret
metadata:
  name: etcd-backup-local
  namespace: default
stringData:
  "hostPath": "/data/etcd/backup"
```

Unfortunately, this is not possible anymore since the switch to the component concept with https://github.com/gardener/etcd-druid/pull/365, it always takes `/etc/gardener/local-backupbuckets` as the standard path.

**Expected behavior:**
The `hostPath` to be configurable.

**Environment (please complete the following information):**
 - Etcd version/commit ID : `v0.12.3`
