### ISSUE TITLE
[Enhancement] Exceptions for `BackupReady` condition 

### ISSUE THREAD

**Issue by timuthy** [gardener/etcd-druid#413]
**Feature (What you would like to be added):**
Today, `Etcd-Druid` maintains the `BackupReady` condition even for `etcd` resources that don't define a backup. Even though the `status` of this conditions remains `Unknown`, we should rather not maintain the condition at all to not cause any confusion.

```
status:
  conditions:
  - lastTransitionTime: "2022-07-28T05:48:24Z"
    lastUpdateTime: "2022-08-22T15:21:11Z"
    message: Cannot determine etcd backup status
    reason: Unknown
    status: Unknown
    type: BackupReady
```

Furthermore, we should correctly maintain the `BackupReady` condition when `etcd.spec.replicas: 0` is set (aka hibernation). Today, the conditions becomes `false`:

```
  - lastTransitionTime: "2022-07-28T05:48:24Z"
    lastUpdateTime: "2022-08-22T15:23:08Z"
    message: Stale snapshot leases. Not renewed in a long time
    reason: BackupFailed
    status: "False"
    type: BackupReady
```
