### ISSUE TITLE
Various Improvement Proposals

### ISSUE THREAD

**Issue by vlerenc** [gardener/etcd-druid#459]
**What you would like to be improved:**
While running zone outage simulations/using etcd-druid directly, I made a few observations that are maybe helpful:

1. Rolling update strategy for today installed druids looks "default":
```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
```

2. Missing label `app` for `podAntiAffinity`:
```
            matchLabels:
              gardener.cloud/role: controlplane
              role: main
```
  should probably be:
```
            matchLabels:
              gardener.cloud/role: controlplane
              app: etcd-statefulset
              role: main
```

3. Outdated label `garden.sapcloud.io` for `selector`:
```
    matchLabels:
      app: etcd-statefulset
      garden.sapcloud.io/role: controlplane
      role: main
```
should probably be:
```
    matchLabels:
      app: etcd-statefulset
      gardener.cloud/role: controlplane
      role: main
```

4. Sometimes, ETCDs have no `ready` state anymore, even if it was ready before and after - it's empty because the status field is not always present, but why:
```
$ kubectl get etcd
NAME        READY   AGE
etcd-main           26m
```
See also #453.
