### ISSUE TITLE
[BUG]  Potential improvements in etcd resource status or  in Custom Columns of etcd resource

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#557]
**Describe the bug:**
When Scale-up scenario fails in middle of scaling up and 1 etcd pod fails to join:
```
etcd-main-0                                   2/2     Running             0             85s
etcd-main-1                                   1/2     Running             0             84s
etcd-main-2                                   2/2     Running             0             83s
```

following etcd status:
```
  status:
    clusterSize: 2
    conditions:
    - lastTransitionTime: "2023-04-25T04:54:29Z"
      lastUpdateTime: "2023-04-25T05:21:42Z"
      message: All members are ready
      reason: AllMembersReady
      status: "True"
      type: AllMembersReady
    - lastTransitionTime: "2023-04-25T04:54:54Z"
      lastUpdateTime: "2023-04-25T05:21:42Z"
      message: Snapshot backup succeeded
      reason: BackupSucceeded
      status: "True"
      type: BackupReady
    - lastTransitionTime: "2023-04-25T04:54:34Z"
      lastUpdateTime: "2023-04-25T05:21:42Z"
      message: The majority of ETCD members is ready
      reason: Quorate
      status: "True"
      type: Ready
    currentReplicas: 1
    etcd:
      apiVersion: apps/v1
      kind: StatefulSet
      name: etcd-main
    members:
    - id: a789d1ab8da2e800
      lastTransitionTime: "2023-04-25T04:54:34Z"
      name: etcd-main-0
      reason: LeaseSucceeded
      role: Leader
      status: Ready
    - id: bda90f379184787e
      lastTransitionTime: "2023-04-25T05:20:52Z"
      name: etcd-main-1
      reason: LeaseSucceeded
      role: Member
      status: Ready
    observedGeneration: 1
    ready: false
    readyReplicas: 2
    replicas: 1
    serviceName: etcd-main-client
    updatedReplicas: 2
```

I observed that etcd `.status.clusterSize: 2` as reason could be scale-up succeeded till `1->2` replicas only and that's why it also sets `AllMembersReady status` as `true` but in `k get etcd -owide` `CLUSTER SIZE` is shown as `3` which IMO is misleading as `ALL MEMBERS READY` column is also set to `True`
```
k get etcd -owide                                                                                                                             
NAME          READY   QUORATE   ALL MEMBERS READY   BACKUP READY   AGE   CLUSTER SIZE   CURRENT REPLICAS   READY REPLICAS
etcd-main     false   True      True                True           3d    3                                 2
```

**Expected behavior:**
Etcd resource status `AllMembersReady` shouldn’t be `true` as 3rd members haven’t join the cluster.

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:
