### ISSUE TITLE
[BUG] Etcd-druid removes the scale-up annotation even if scale-up didn't succeed.

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#582]
**Describe the bug:**
Etcd-druid controller removes the scale-up annotation `gardener.cloud/scaled-to-multi-node` from etcd-statefulset when 2nd member join the cluster but 3rd member fails to join the cluster. 
[clusterScaledUpToMultiNode](https://github.com/gardener/etcd-druid/blob/e30729fec708580f5203de9520a2415c8765a3b5/pkg/component/etcd/statefulset/statefulset.go#L287-L292) wrongly returns false as `sts.Spec.Replicas` is no longer equal to `1`.
```
k get sts etcd-main -oyaml | grep replicas -C 5
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      instance: etcd-main
      name: etcd
--
  collisionCount: 0
  currentReplicas: 1
  currentRevision: etcd-main-64b8bbd7f7
  observedGeneration: 2
  readyReplicas: 2
  replicas: 3
  updateRevision: etcd-main-6479474444
  updatedReplicas: 2
```

**Expected behavior:**
etcd-druid controller shouldn't removes the scale-up annotation `gardener.cloud/scaled-to-multi-node` until all members (defined by `.spec.replicas`) joins the cluster.

**How To Reproduce (as minimally and precisely as possible):**
1. Start the etcd-cluster deployed by druid with `.spec.replicas` = 1
2. Now, update the `.spec.replicas` to 3 in etcd custom resource
3. Don't let 1 of etcd member to join the cluster and let the other 1 member to join the cluster.
4. you can check the etcd statefulset yaml that `gardener.cloud/scaled-to-multi-node` has been removed.

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:
