### ISSUE TITLE
[BUG] Wrong `.status.replicas` is set in etcd resource when cluster is marked for scale-up

### ISSUE THREAD

**Issue by ishan16696** [gardener/etcd-druid#583]
**Describe the bug:**
Wrong `.status.replicas` is being set in etcd resource when cluster is marked for scale-up and if scale-up didn't succeed

etcd.status:
```
  status:
    clusterSize: 2
    conditions:
    - lastTransitionTime: "2023-04-21T07:21:19Z"
      lastUpdateTime: "2023-04-21T07:30:49Z"
      message: All members are ready
      reason: AllMembersReady
      status: "True"
      type: AllMembersReady
    - lastTransitionTime: "2023-04-21T07:21:44Z"
      lastUpdateTime: "2023-04-21T07:30:49Z"
      message: Snapshot backup succeeded
      reason: BackupSucceeded
      status: "True"
      type: BackupReady
    - lastTransitionTime: "2023-04-21T07:21:21Z"
      lastUpdateTime: "2023-04-21T07:30:49Z"
      message: The majority of ETCD members is ready
      reason: Quorate
      status: "True"
      type: Ready
    currentReplicas: 1
    etcd:
      apiVersion: apps/v1
      kind: StatefulSet
      name: etcd-main
    members:
    - id: a789d1ab8da2e800
      lastTransitionTime: "2023-04-21T07:21:21Z"
      name: etcd-main-0
      reason: LeaseSucceeded
      role: Leader
      status: Ready
    - id: 7318567c4b8544d3
      lastTransitionTime: "2023-04-21T07:22:47Z"
      name: etcd-main-1
      reason: LeaseSucceeded
      role: Member
      status: Ready
    observedGeneration: 1
    ready: false
    readyReplicas: 2
    replicas: 1
    serviceName: etcd-main-client
    updatedReplicas: 2
```

**Expected behavior:**

**How To Reproduce (as minimally and precisely as possible):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:
