### ISSUE TITLE
[BUG] etcd stuck during restore after redeploying the etcd instance CR

### ISSUE THREAD

**Issue by lizzzcai** [gardener/etcd-druid#621]
**Describe the bug:**

etcd instance (3 replicas) cannot be restored after deleting the instance CR and PVC and creating the instance CR again.

**Expected behavior:**

etcd instance should be able to be restored after deleting instance CR and the PVC.

**How To Reproduce (as minimally and precisely as possible):**
1. create a etcd instance with 3 replicas.
2. add some data into etcd service, wait for backup.
3. once can see full backup and incremental backup in the remote storage, delete the etcd CR and delete the PVC.
4. create the same etcd instance again.

etcd instance, tls can be removed.
```
apiVersion: druid.gardener.cloud/v1alpha1
kind: Etcd
metadata:
  name: modelmesh-etcd-service
  namespace: modelmesh-etcd
spec:
  backup:
    compression:
      enabled: false
      policy: gzip
    deltaSnapshotMemoryLimit: 1Gi
    deltaSnapshotPeriod: 300s
    fullSnapshotSchedule: 0 */24 * * *
    garbageCollectionPeriod: 43200s
    garbageCollectionPolicy: Exponential
    image: eu.gcr.io/gardener-project/gardener/etcdbrctl:v0.24.1
    leaderElection:
      etcdConnectionTimeout: 5s
      reelectionPeriod: 5s
    port: 8080
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    store:
      container: xxxxxxxx
      prefix: xxxxxxxx
      provider: aws
      secretRef:
        name: aws-etcd-secret
    tls:
      clientTLSSecretRef:
        name: etcd-client-certificate
        namespace: modelmesh-etcd
      serverTLSSecretRef:
        name: etcd-server-certificate
        namespace: modelmesh-etcd
      tlsCASecretRef:
        dataKey: ca.crt
        name: etcd-client-certificate
        namespace: modelmesh-etcd
  etcd:
    clientPort: 2379
    clientUrlTls:
      clientTLSSecretRef:
        name: etcd-client-certificate
        namespace: modelmesh-etcd
      serverTLSSecretRef:
        name: etcd-server-certificate
        namespace: modelmesh-etcd
      tlsCASecretRef:
        dataKey: ca.crt
        name: etcd-client-certificate
        namespace: modelmesh-etcd
    defragmentationSchedule: 0 */24 * * *
    heartbeatDuration: 10s
    image: eu.gcr.io/gardener-project/gardener/etcd:v3.4.13-bootstrap-10
    metrics: basic
    peerUrlTls:
      serverTLSSecretRef:
        name: etcd-server-certificate
        namespace: modelmesh-etcd
      tlsCASecretRef:
        dataKey: ca.crt
        name: etcd-server-certificate
        namespace: modelmesh-etcd
    quota: 8Gi
    resources:
      limits:
        cpu: 2
        memory: 4Gi
      requests:
        cpu: 2
        memory: 4Gi
    serverPort: 2380
  labels:
    app.kubernetes.io/component: etcd
    app.kubernetes.io/instance: modelmesh-etcd-service
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: etcd
    helm.sh/chart: etcd-8.5.7
  replicas: 3
  schedulingConstraints:
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: etcd
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
    - labelSelector:
        matchLabels:
          app.kubernetes.io/instance: etcd
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
  selector:
    matchLabels:
      app.kubernetes.io/component: etcd
  sharedConfig:
    autoCompactionMode: periodic
    autoCompactionRetention: 30m
  storageCapacity: 12Gi
  storageClass: default
```

**Logs:**

logs of the bakcup-restore container in etcd-0: 
[etcd-backup-restore.log](https://github.com/gardener/etcd-druid/files/11788672/etcd-backup-restore.log)

pod spec of the etcd-0: 

```sh
❯ k get etcd -n modelmesh-etcd modelmesh-etcd-service
NAME                     READY   QUORATE   ALL MEMBERS READY   BACKUP READY   AGE
modelmesh-etcd-service   false   Unknown   Unknown             Unknown        27m
❯ k get po -n modelmesh-etcd
NAME                                              READY   STATUS    RESTARTS   AGE
modelmesh-etcd-service-0                          1/2     Running   0          27m
modelmesh-etcd-service-1                          1/2     Running   0          27m
modelmesh-etcd-service-2                          1/2     Running   0          27m
```

status of the etcd cr:
```
  status:
    conditions:
    - lastTransitionTime: "2023-06-19T13:10:09Z"
      lastUpdateTime: "2023-06-19T13:25:44Z"
      message: Cannot determine readiness since status has no members
      reason: NoMembersInStatus
      status: Unknown
      type: AllMembersReady
    - lastTransitionTime: "2023-06-19T13:10:09Z"
      lastUpdateTime: "2023-06-19T13:25:44Z"
      message: Cannot determine etcd backup status
      reason: Unknown
      status: Unknown
      type: BackupReady
    - lastTransitionTime: "2023-06-19T13:10:09Z"
      lastUpdateTime: "2023-06-19T13:25:44Z"
      message: Cannot determine readiness of cluster since no cluster size has been
        calculated
      reason: ClusterSizeUnknown
      status: Unknown
      type: Ready
    currentReplicas: 3
    etcd:
      apiVersion: apps/v1
      kind: StatefulSet
      name: modelmesh-etcd-service
    ready: false
    updatedReplicas: 3
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID : `eu.gcr.io/gardener-project/gardener/etcd:v3.4.13-bootstrap-10`
 - Etcd backup restore: `eu.gcr.io/gardener-project/gardener/etcdbrctl:v0.24.1`
 - Etcd-druid version/commit ID : v0.18.1
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: AWS

**Anything else we need to know?**:

if I remove all the backup restore in the cloud storage and redeploy the etcd, it will be up and running
